spring:
   datasource:
      username: restaurant
      password: restaurant
      url: jdbc:mysql://localhost:3306/restaurant
      

   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
   